spring.application.name=history-prices

# H2 Database Configuration
spring.datasource.url=jdbc:h2:mem:pricesdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Hibernate
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=none
spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:schema.sql
spring.sql.init.data-locations=classpath:data.sql

# H2 Console Configuration
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Show SQL statements in the console
spring.jpa.show-sql=true

# application.properties
springdoc.swagger-ui.urls[0].name=Historical Prices API
springdoc.swagger-ui.urls[0].url=/openapi.yaml
springdoc.swagger-ui.path=/api/swagger
springdoc.api-docs.path=/api/api-docs